services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env # <-- Mounts backend .env into container
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - ./frontend/.env:/app/.env # <-- Mounts frontend .env into container
    networks:
      - app-network

networks:
  app-network:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd00::/80
