name: Scheduled ETL Process

on:
  schedule:
    - cron: '0 * * * *'  # hourly
  workflow_dispatch:      # allow manual triggering
    inputs:
      user:
        description: 'User triggering the workflow'
        required: false
        default: 'GitHub Actions'

jobs:
  etl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run ETL Process
      working-directory: ./backend
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PYTHONPATH: .
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "Manual trigger by ${{ github.actor }} at $(date -u '+%Y-%m-%d %H:%M:%S')"
          python -m app.cli
        else
          echo "Scheduled run at $(date -u '+%Y-%m-%d %H:%M:%S')"
          python -m app.cli
        fi
